import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/options";
import SessionProvider from "../Context/SessionProvider";
import AppContextProvider from "../Context/AppContextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ChatGPT",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gptGray text-gptWhite `}>
        <SessionProvider session={session}>
          <AppContextProvider>{children}</AppContextProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
